packages:
  - "."

strictDepBuilds: false
dangerouslyAllowAllBuilds: true

onlyBuiltDependencies:
  - "@google/genai"
  - "esbuild"
  - "protobufjs"

allowBuilds:
  - "@google/genai"
  - "esbuild"
  - "protobufjs"
